spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: exchange-demosb
  cloud:
    config:
      name: exchange-demosb
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false

info:
  project:
    name: Mantenimiento Cambio de Moneda V1
    description: Microservicio de mantenimiento Cambio de Moneda
    version: 1.0.0

application:
  client:
    api:
      path: "/channel/exchange/v1"
      pathExchange: "/exchange"
  parameter:
    message:
      correcto: 'Ejecución correcta.'
      errorGenerico: 'Ocurrió un error inesperado.'
springfox:
  documentation:
    swagger:
      v2:
        path: "/channel/exchange/v1/swagger/swagger2.json"

management:
  endpoints:
    web:
      base-path: "/channel/exchange/v1/actuator"

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      jwt:
        key-uri: http://localhost:8090/oauth/token_key
    client:
      client-id: trusted_client_id
      client-secret: password
      access-token-uri: http://localhost:8090/oauth/token
      grantType: password

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG

server:
  port: 8090